"""
Pytest / tftest smoke tests for tf-iac-storage-module.

Prerequisites:
    pip install pytest tftest

Run:
    pytest -v tests/
"""

import os
from pathlib import Path

import pytest

try:
    import tftest

    TFTEST_AVAILABLE = True
except ImportError:
    TFTEST_AVAILABLE = False

_ROOT = Path(__file__).parent.parent
_TFVARS = str(_ROOT / "tests" / "fixtures" / "terraform.tfvars")


@pytest.mark.skipif(not TFTEST_AVAILABLE, reason="tftest not installed")
class TestStorageModule:
    """Plan-level validation for the storage module via examples/basic."""

    @pytest.fixture(scope="class")
    def plan(self):
        tf = tftest.TerraformTest(
            tfdir=str(_ROOT / "examples" / "basic"),
            env={
                **os.environ,
                "TF_CLI_ARGS_init": "-backend=false",
                "TF_CLI_ARGS_plan": "-lock=false",
            },
        )
        tf.setup(extra_files=[_TFVARS])
        yield tf.plan(output=True)

    # ── Plan health ───────────────────────────────────────────────────────────

    def test_plan_succeeds(self, plan):
        assert plan is not None

    # ── Storage Account ───────────────────────────────────────────────────────

    def test_storage_account_present(self, plan):
        assert "module.storage.azurerm_storage_account.this[0]" in plan.resource_changes

    def test_storage_account_action_create(self, plan):
        sa = plan.resource_changes["module.storage.azurerm_storage_account.this[0]"]
        assert "create" in sa["change"]["actions"]

    def test_storage_account_name_from_naming_module(self, plan):
        """Name is generated by Azure/naming (random suffix = known_after_apply)."""
        sa = plan.resource_changes["module.storage.azurerm_storage_account.this[0]"]
        # random_string is resolved at apply time, so the full name is deferred;
        # the plan marks it as known_after_apply rather than populating after["name"].
        assert sa["change"]["after_unknown"].get("name") is True, (
            "Storage account name must be known_after_apply (sourced from naming module)"
        )

    def test_tls_version_enforced(self, plan):
        sa = plan.resource_changes["module.storage.azurerm_storage_account.this[0]"]
        assert sa["change"]["after"]["min_tls_version"] == "TLS1_2"

    # ── Containers ────────────────────────────────────────────────────────────

    def test_uploads_container_present(self, plan):
        assert 'module.storage.azurerm_storage_container.this["uploads"]' in plan.resource_changes

    def test_container_action_create(self, plan):
        containers = [
            v for k, v in plan.resource_changes.items()
            if "azurerm_storage_container" in k
        ]
        assert len(containers) >= 1
        for c in containers:
            assert "create" in c["change"]["actions"]

    # ── Naming module ─────────────────────────────────────────────────────────

    def test_naming_random_resources_present(self, plan):
        naming_resources = [k for k in plan.resource_changes if "naming.random_string" in k]
        assert len(naming_resources) >= 1, "Expected random_string resources from naming module"

    # ── Outputs ───────────────────────────────────────────────────────────────

    def test_outputs_declared(self, plan):
        assert "storage_account_name" in plan.outputs
        assert "primary_blob_endpoint" in plan.outputs
