name: CD - Deploy Dev

on:
  push:
    branches: [main]
    paths:
      - "envs/dev/**"

jobs:
  apply-dev:
    name: Apply (dev)
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - uses: dflook/terraform-apply@v1
        with:
          path: envs/dev
          auto_approve: true
        env:
          TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          TF_VAR_mysql_admin_password: ${{ secrets.TF_VAR_MYSQL_ADMIN_PASSWORD }}
