name: Module Tests

on:
  push:
    branches: ["**"]
    paths:
      - "**-module/**"
  pull_request:
    branches: ["**"]
    paths:
      - "**-module/**"
  workflow_dispatch:
    inputs:
      test_type:
        description: "Test type"
        required: false
        default: plan
        type: choice
        options:
          - plan
          - e2e
          - all

jobs:
  test:
    uses: btdmsd/github-actions-workflows/.github/workflows/module-tests.yml@main
    with:
      test_type: ${{ inputs.test_type || 'plan' }}
    secrets: inherit
