name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semantic version tag (e.g. v1.0.1)"
        required: true

jobs:
  tag:
    name: Tag release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create and push tag
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}
